# Generated by Django 5.2 on 2025-05-18 18:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 (worst) to 5 (best)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional review comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether this time slot is active')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
                'ordering': ['doctor', 'day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Full mailing address'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profiles/avatars/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or profile summary'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Toggle if the doctor is currently active'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(blank=True, help_text='Medical license or registration number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='qualifications',
            field=models.CharField(blank=True, help_text='Comma-separated qualifications/degrees', max_length=255),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=0, help_text='Total years in clinical practice'),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Full mailing address'),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profiles/avatars/'),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or profile summary'),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='shift_end',
            field=models.TimeField(blank=True, help_text='Daily shift end time', null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='shift_start',
            field=models.TimeField(blank=True, help_text='Daily shift start time', null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(help_text="Medical specialty, e.g., 'Cardiology'", max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': False}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': False}, on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['specialty'], name='profiles_do_special_5db6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['license_number'], name='profiles_do_license_3b99eb_idx'),
        ),
        migrations.AddIndex(
            model_name='receptionistprofile',
            index=models.Index(fields=['shift_start', 'shift_end'], name='profiles_re_shift_s_ce7385_idx'),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='User who submitted the review', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='profiles.doctorprofile'),
        ),
        migrations.AddIndex(
            model_name='doctorreview',
            index=models.Index(fields=['doctor'], name='profiles_do_doctor__ae6552_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('doctor', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
