# Generated by Django 5.2 on 2025-07-21 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_doctorreview_timetableentry_doctorprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('education', 'Education'), ('internship', 'Internship'), ('certification', 'Certification')], max_length=20)),
                ('name', models.CharField(help_text='Degree, Certification, or Internship Name', max_length=255)),
                ('institution', models.CharField(blank=True, help_text='Where it was earned', max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, help_text='Additional info (optional)')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='doctorprofile',
            name='profiles_do_special_5db6e6_idx',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='specialty',
            new_name='main_specialty',
        ),
        migrations.AddField(
            model_name='achievement',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='profiles.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='other_specialties',
            field=models.ManyToManyField(blank=True, help_text='Other specialties for the doctor', related_name='doctors', to='profiles.specialty'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['main_specialty'], name='profiles_do_main_sp_c727ea_idx'),
        ),
    ]
